FROM ubuntu:20.04

ENV TZ=Europe/Amsterdam
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN apt-get update && apt-get install -y \
	openjdk-8-jdk-headless \
	iputils-ping \
	net-tools \
	telnet \
	zip \
	unzip \
	tzdata \
	vim
